---

language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible
  - pip install ansible

  # Fix roles_path
  - "printf '[defaults]\nroles_path=../' > ansible.cfg"
  #- cp tests/ansible.cfg ./

script:
  # Check Syntax
  - ansible-galaxy install -c  Stouts.mongodb
  - ansible-galaxy install -c  Stouts.nodejs
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
    
