---
- group: name=strider state=present

- name: Create user strider 
  sudo: yes
  user: name=strider comment="strider" group=strider groups=sudo home=/home/strider createhome=yes  state=present

- apt: name={{item}} state=present 
  with_items: 
     - git 
     - python-virtualenv
     - python-dev 
     - git 
     - g++ 
     - make 

## has error when pure npm install :( 
- shell: "npm install --global=yes  --unsafe-perm strider"
  sudo: yes

# install strider init file
- template: src=strider.conf.j2 dest=/etc/init/strider.conf
  sudo: yes
