Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.ssh
  config.ssh.forward_agent=false
  #config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "hashicorp/precise64"
  #config.vm.box = "chef/centos-6.5"
  #config.vm.box = "chef/debian-7.4"

  config.vm.network :private_network, ip: "192.168.33.111"
  config.vm.network "forwarded_port", guest: 4000, host: 4000, auto_correct: true


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.sudo = true
    ansible.verbose= "v"
    ansible.host_key_checking = false 
    ansible.extra_vars = { ansible_ssh_user: 'vagrant', 
                 ansible_connection: 'paramiko',
                 #ansible_ssh_args: '-o ForwardAgent=yes'}
                 ansible_ssh_args: ''}
  end
end
